### ISSUE TITLE
[Bug-001]: Can't take picture after returning from a detail view on NavigationView

### ISSUE THREAD

**Issue by moh-abk** [rorodriguez116/Camera-SwiftUI#1]
Great package! - I discovered a bug. When I move to a new view using `NavigationLink` and then use the `back` navigationBarButton to return to the camera view - it is no longer possible to take an image; and `Couldn't add video device input to the session.` is printed in the console.

**Comment by rorodriguez116** [comment]
Thank you! I will review and try to reproduce the error.

**Comment by lekt9** [comment]
Can confirm that this issue is happening for me as well.

**Comment by viktor-savchik-idf** [comment]
I've faced with the same issue

**Comment by bandtank** [comment]
Does anyone have a workaround for this? I have not been able to figure out how to fix or avoid the issue.

**Comment by SylarRuby** [comment]
Anyone found out how to fix this? It's the same with Apple's [AVCam app](https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/avcam_building_a_camera_app).

**Comment by wailbabou** [comment]
I faced this issue with `NavigationLink` and I fixed it by calling `model.configure()` only once , and calling `session.stopRunning()` and   `session.startRunning()`  in `CameraPreview` `onAppear`

**Comment by wailbabou** [comment]
This fixed the problem for me : 
- in `CameraService` remove `self.start()` from `configureSession()`

And : 

```swift
    func isConfigured() -> Bool {
        return service.isConfigured
    }
    
    func start(){
        service.start()
    }
    func stop(){
        service.stop()
    }
```
 
```swift
CameraPreview(session: model.session)
                        .onAppear {
                            print("isConfigured = \(model.isConfigured())")
                            if !model.isConfigured() {
                                model.configure()
                            }
                            model.start()
                        }
```

**Comment by rorodriguez116** [comment]
This issue has been fixed please see this [PR](https://github.com/rorodriguez116/Camera-SwiftUI/pull/7).
