### ISSUE TITLE
Focus Tap Indicator Not Centered on Tap Location

### ISSUE THREAD

**Issue by achi113s** [rorodriguez116/Camera-SwiftUI#11]
CameraPreview.swift: The circle that appears when you tap to focus does not appear at the location of the tap. Instead it appears slightly off center due to the origin of the circle being at the top left corner. Proposed solution is to just offset the circle in x and y by its radius. Should just modify the focusView's CGRect to this:

```
let focusCircleDiam: CGFloat = 50
let shiftedLayerPoint = CGPoint(
                x: layerPoint.x - (focusCircleDiam / 2),
                y: layerPoint.y - (focusCircleDiam / 2))
            
self.focusView.layer.frame = CGRect(origin: shiftedLayerPoint, size: CGSize(width: focusCircleDiam, height: focusCircleDiam))
```

**Comment by rorodriguez116** [comment]
Thanks for pointing this out, I'll take a look.

**Comment by rorodriguez116** [comment]
Thanks, this fixes the issue will update main branch.
