### ISSUE TITLE
bug: Couldn't add video device input to the session.

### ISSUE THREAD

**Issue by lekt9** [rorodriguez116/Camera-SwiftUI#5]
When following this [guide](https://www.hackingwithswift.com/quick-start/swiftui/how-to-create-scrolling-pages-of-content-using-tabviewstyle) to recreate a Snapchat-like navigation for my app, I stumbled upon "Couldn't add video device input to the session." when using the following code:

`TabView(){
      CameraPreview(session: model.session)
      .onAppear {
            model.configure()
      }
.tabViewStyle(PageTabViewStyle())
`

**Comment by lekt9** [comment]
I believe this has to do with model.configure() occuring on .onAppear, which seems to have a problem with PageTabViewStyle()

**Comment by rorodriguez116** [comment]
Hi @lewistham9x this issue has been fixed please see this [PR](https://github.com/rorodriguez116/Camera-SwiftUI/pull/7)
